import Link from "next/link";
import { CheckCircle2, Bot, Layers } from "lucide-react";

export default function AgentInsightsArtifact() {
  return (
    <div className="space-y-12 py-8 max-w-4xl mx-auto">
      <Link href="/work/entelligence" className="text-xs font-mono text-[var(--n-playhead)] hover:underline">
        ← Back to Entelligence AI Case Study
      </Link>

      <div className="space-y-4">
        <div className="flex items-center justify-between text-xs font-mono text-[var(--n-muted)]">
          <span className="text-[var(--n-playhead)] font-semibold">ENTELLIGENCE AI // ARTIFACT</span>
          <span>PRODUCT UX</span>
        </div>
        <h1 className="text-4xl sm:text-5xl font-medium tracking-tight text-[var(--n-ink)]">
          DeepReviews & Agent Insights UX
        </h1>
        <p className="text-lg text-[var(--n-graphite)] font-serif italic">
          Designing the experience for an AI code review engine that reads full codebase history.
        </p>
      </div>

      <div className="p-8 rounded-[var(--n-radius-panel)] border border-[var(--n-line)] bg-[var(--n-paper)] space-y-6 shadow-xs font-mono text-xs">
        <div className="flex justify-between items-center text-[var(--n-muted)] border-b border-[var(--n-line-soft)] pb-4">
          <span>SURFACE: DeepReviews / PR Reviewer</span>
          <span className="text-[var(--n-playhead)] font-semibold flex items-center gap-1">
            <CheckCircle2 className="w-3.5 h-3.5" /> SHIPPED PRODUCT
          </span>
        </div>

        <div className="space-y-4 text-sm text-[var(--n-graphite)] font-sans leading-relaxed">
          <p>
            When code is generated by AI, classic syntax linters aren't enough. Entelligence's DeepReviews cross-checks pull requests against the engineering team's past incident logs, catching architectural regression bugs before merge.
          </p>

          <h3 className="text-base font-bold text-[var(--n-ink)] font-mono pt-2">UX Challenges & Decisions:</h3>
          <ul className="list-disc list-inside space-y-2 font-mono text-xs text-[var(--n-graphite)]">
            <li><strong>High-Density Information Architecture:</strong> Structured split views for multi-file diffs without overwhelming dev leads.</li>
            <li><strong>Incident Provenance:</strong> Every flagged bug links directly back to the exact historical production incident that caused it.</li>
            <li><strong>Confidence Rating UI:</strong> Subdued, color-coded indicators so developers immediately know high-severity risks vs minor suggestions.</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
