import { CheckCircle2 } from "lucide-react";
import { ArtifactLayout, FeatureBulletList } from "@/components/ArtifactLayout";

export default function AgentInsightsArtifact() {
  const uxFeatures = [
    { label: "High-Density Information Architecture", text: "Structured split views for multi-file diffs without overwhelming dev leads." },
    { label: "Incident Provenance", text: "Every flagged bug links directly back to the exact historical production incident that caused it." },
    { label: "Confidence Rating UI", text: "Subdued, color-coded indicators so developers immediately know high-severity risks vs minor suggestions." },
  ];

  return (
    <ArtifactLayout
      backHref="/work/entelligence"
      backLabel="← Back to Entelligence AI Case Study"
      category="ENTELLIGENCE AI // ARTIFACT"
      tag="PRODUCT UX"
      title="DeepReviews & Agent Insights UX"
      subtitle="Designing the experience for an AI code review engine that reads full codebase history."
    >
      <div className="p-8 rounded-[var(--n-radius-panel)] border border-[var(--n-line)] bg-[var(--n-paper)] space-y-6 shadow-xs font-mono text-xs">
        <div className="flex justify-between items-center text-[var(--n-muted)] border-b border-[var(--n-line-soft)] pb-4">
          <span>SURFACE: DeepReviews / PR Reviewer</span>
          <span className="text-[var(--n-ink)] font-semibold flex items-center gap-1">
            <CheckCircle2 className="w-3.5 h-3.5" /> SHIPPED PRODUCT
          </span>
        </div>

        <div className="space-y-4 text-sm text-[var(--n-graphite)] font-sans leading-relaxed">
          <p>
            When code is generated by AI, classic syntax linters aren't enough. Entelligence's DeepReviews cross-checks pull requests against the engineering team's past incident logs, catching architectural regression bugs before merge.
          </p>

          <h3 className="text-base font-bold text-[var(--n-ink)] font-mono pt-2">UX Challenges & Decisions:</h3>
          <FeatureBulletList items={uxFeatures} />
        </div>
      </div>
    </ArtifactLayout>
  );
}
